# Generated by Django 4.2.4 on 2023-08-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('haplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LehrerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(default='0', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lehrerpost_images/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_post',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='users', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('klasse', models.CharField(max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('deadline', models.DateTimeField()),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
