# Generated by Django 4.2.4 on 2023-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='klasse',
            field=models.TextField(default='9c', max_length=2),
            preserve_default=False,
        ),
    ]
