# Generated by Django 4.2.4 on 2023-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0005_post_klasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_id',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='klasse',
            field=models.CharField(max_length=2),
        ),
    ]
