# Generated by Django 4.2.4 on 2023-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0006_alter_customuser_school_id_alter_post_klasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_post',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
    ]
