# Generated by Django 4.2.4 on 2023-08-10 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0012_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LehrerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('bild', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LehrerPosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
