# Generated by Django 4.2.4 on 2023-08-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0002_lehrerpost_customuser_can_post_customuser_is_teacher_and_more'),
        ('haplus', '0013_lehrerpost'),
    ]

    operations = [
    ]
