# Generated by Django 4.2.4 on 2023-08-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haplus', '0014_merge_20230819_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LehrerPost',
        ),
    ]
