version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: HausaufgabenPlus.settings
      DATABASE_URL: sqlite:////app/db.sqlite3
